---
all:
  vars:
    ansible_connection: ssh
    ansible_user: alexd
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 178.154.234.133
kibana:
  hosts:
    k-instance:
      ansible_host: 178.154.234.28
app:
  hosts:
    application-instance: 
      ansible_host: 178.154.235.96